server:
  port: 8080
  servlet:
    context-path: /vexium

spring:
  application:
    name: vexium-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-v0gmsrszibirwhyd.us.auth0.com/
          jwk-set-uri: https://dev-v0gmsrszibirwhyd.us.auth0.com/.well-known/jwks.json

  datasource:
    url: jdbc:postgresql://localhost:5432/fit_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: false

app:
  mercadopago:
    access-token: APP_USR-1756198843857397-071316-5dd3feb3465105c2fe46030449156be4-3538197051

  qr:
    size: 300
    format: PNG
  notificaciones:
    dias-aviso-primero: 7
    dias-aviso-segundo: 1
  auth0:
    audience: https://vexium-api.com