server:
  port: 8080
  servlet:
    context-path: /vexium

spring:
  application:
    name: vexium-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-v0gmsrszibirwhyd.us.auth0.com/
          audience: https://vexium-api.com

  datasource:
    url: jdbc:postgresql://localhost:5432/fit_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: false
